services:
    mongodb:
        image: mongo:latest
        environment:
            - MONGO_INITDB_DATABASE=mydatabase
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=secret
        ports:
            - '27017:27017'
        volumes:
            - mongodb_data:/data/db

volumes:
    mongodb_data:
        driver: local