spring:
    application:
        name: spring-practice-mongodb-gridfs
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB

    data:
        mongodb:
            database: mydatabase
            host: localhost
            port: 27017
            username: root
            password: secret


logging:
    level:
        org.springframework.data.mongodb: DEBUG