spring:
    application:
        name: spring-practice-mongodb-gridfs
    threads:
        virtual:
            enabled: true
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB

    data:
        mongodb:
            uri: mongodb://root:secret@localhost:27017/mydatabase?authSource=admin

logging:
    level:
        org.springframework.data.mongodb: DEBUG